"""
Django settings for chemview_website project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from enum import Enum, auto

import dj_database_url


class PlaidMode(Enum):
    SANDBOX = auto()
    PRODUCTION = auto()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEPLOYED = True if "DATABASE_URL" in os.environ else False

PLAID_MODE = PlaidMode.SANDBOX

if DEPLOYED:
    DEBUG = False
    DEBUG = True  # todo temp
    SECRET_KEY = os.environ["SECRET_KEY"]

    SENDGRID_KEY = os.environ["SENDGRID_KEY"]

    PLAID_MODE = PlaidMode.PRODUCTION
    PLAID_CLIENT_ID = os.environ["PLAID_CLIENT_ID"]
    PLAID_SECRET = os.environ["PLAID_SECRET"]
else:
    DEBUG = True
    SECRET_KEY = "django-insecure-kt#8(6pid*k1u6b9!yh(70^7s41ydqu=_!#%l79n8nm-os*$b)"

    try:
        from .private import SENDGRID_KEY
    # Allow an escape hatch so the problem runs and can be tested with a quick
    # git pull. Email is non-functional here.
    except ImportError:
        SENDGRID_KEY = ""

    PLAID_SECRET = None
    PLAID_CLIENT_ID = None

    try:
        from main import private
    # Allow an escape hatch so the problem runs and can be tested with a quick
    # git pull. Email is non-functional here.
    except ImportError:
        pass  # Leave this config vars at their initialized-to-None values above.
    else:
        try:
            PLAID_CLIENT_ID = private.PLAID_CLIENT_ID

            if PLAID_MODE == PlaidMode.SANDBOX:
                PLAID_SECRET = private.PLAID_SECRET_SANDBOX
            else:
                PLAID_SECRET = private.PLAID_SECRET_PRODUCTION

        # This AttributeError happens if values are missing from `private.py`.
        except AttributeError:
            print(
                "One or more Plaid (Account aggregator) keys missing from `private.py`. If unavailable, set them to be empty strings, and try again."
            )
            pass

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "financial-monitor-783ae5ca6965.herokuapp.com",
    "finance-monitor.com",
    "www.finance-monitor.com",
]

# Application definition

INSTALLED_APPS = [
    "main.apps.MainConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "wallet.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wallet.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASE_URL = "postgres://postgres:test@localhost:5432/wallet"
DATABASES = {"default": dj_database_url.config(default=DATABASE_URL)}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = "staticfiles"
STATIC_URL = "static/"

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


ADMINS = (("admin", "contact@finance-monitor.com"),)
MANAGERS = ADMINS

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"  # I don't think this is currently used.

if DEPLOYED:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_HOST_USER = "apikey"
EMAIL_HOST_PASSWORD = SENDGRID_KEY
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Using this logging while not deployed causes spam in the dev server console
if DEPLOYED:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "filters": {
            "require_debug_false": {
                "()": "django.utils.log.RequireDebugFalse",
            },
            "require_debug_true": {
                "()": "django.utils.log.RequireDebugTrue",
            },
        },
        "formatters": {
            "django.server": {
                "()": "django.utils.log.ServerFormatter",
                "format": "[%(server_time)s] %(message)s",
            }
        },
        "handlers": {
            "console": {
                "level": "INFO",
                "filters": ["require_debug_true"],
                "class": "logging.StreamHandler",
            },
            "console_debug_false": {
                "level": "ERROR",
                "filters": ["require_debug_false"],
                "class": "logging.StreamHandler",
            },
            "django.server": {
                "level": "INFO",
                "class": "logging.StreamHandler",
                "formatter": "django.server",
            },
            "mail_admins": {
                "level": "ERROR",
                "filters": ["require_debug_false"],
                "class": "django.utils.log.AdminEmailHandler",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console", "mail_admins"],
                "level": "INFO",
            },
            "django.server": {
                "handlers": ["django.server"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }
