# Generated by Django 5.0.2 on 2024-02-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("plaid_id", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("access_token", models.CharField(max_length=100)),
                ("item_id", models.CharField(max_length=100)),
                ("last_refreshed", models.DateTimeField()),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutions",
                        to="main.institution",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="main.person",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaid_id", models.CharField(max_length=100)),
                (
                    "plaid_id_persistent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "name_official",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "DEPOSITORY"),
                            (2, "INVESTMENT"),
                            (3, "LOAN"),
                            (4, "CREDIT"),
                        ]
                    ),
                ),
                (
                    "sub_type",
                    models.IntegerField(
                        choices=[
                            (0, "CHECKING"),
                            (1, "SAVINGS"),
                            (2, "DEBIT_CARD"),
                            (3, "CREDIT_CARD"),
                            (4, "T401K"),
                            (5, "STUDENT"),
                            (6, "MORTGAGE"),
                            (7, "CD"),
                        ]
                    ),
                ),
                ("iso_currency_code", models.CharField(max_length=5)),
                ("available", models.FloatField(blank=True, null=True)),
                ("current", models.FloatField(blank=True, null=True)),
                ("limit", models.FloatField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_accounts",
                        to="main.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("description", models.TextField()),
                ("dt", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="main.subaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["dt"],
            },
        ),
    ]
