# Generated by Django 5.0.2 on 2024-02-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_financialaccount_name_alter_subaccount_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subaccount",
            name="name_official",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
