# Generated by Django 4.2.4 on 2024-02-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_institution_plaid_id_financialaccount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialaccount",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="institution",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["dt"]},
        ),
    ]
