# Generated by Django 4.2.4 on 2024-02-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_financialaccount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="last_refreshed",
            field=models.DateTimeField(default="2024-01-02"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="main.financialaccount",
            ),
        ),
    ]
