# Generated by Django 4.2.4 on 2024-02-29 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_financialaccount_last_refreshed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaid_id", models.CharField(max_length=100)),
                ("plaid_id_persistent", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=30)),
                ("name_official", models.CharField(max_length=30)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "CHECKING"),
                            (1, "SAVINGS"),
                            (2, "DEBIT_CARD"),
                            (3, "CREDIT_CARD"),
                            (4, "T401K"),
                            (5, "STUDENT"),
                            (6, "MORTGAGE"),
                            (7, "CD"),
                        ]
                    ),
                ),
                ("balance", models.FloatField(blank=True, null=True)),
                ("current", models.FloatField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_accounts",
                        to="main.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
