# Generated by Django 5.0.2 on 2024-02-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_person_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="account_locked",
            field=models.BooleanField(default=False),
        ),
    ]
