# Generated by Django 5.0.2 on 2024-02-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_person_account_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="unsuccessful_login_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
