# Generated by Django 4.2.4 on 2024-02-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_subaccount_sub_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subaccount",
            name="limit",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
