# Generated by Django 5.0.2 on 2024-03-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_person_unsuccessful_login_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="plaid_cursor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
