# Generated by Django 4.2.4 on 2024-02-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_subaccount_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subaccount",
            old_name="balance",
            new_name="available",
        ),
    ]
