# Generated by Django 5.0.2 on 2024-03-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_financialaccount_plaid_cursor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccount",
            name="plaid_cursor",
            field=models.CharField(default="", max_length=256),
        ),
    ]
