# Generated by Django 4.2.4 on 2024-02-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_balance_subaccount_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="subaccount",
            name="iso_currency_code",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
