# Generated by Django 4.2.4 on 2024-02-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_subaccount_iso_currency_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subaccount",
            name="name_official",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
