# Generated by Django 5.0.2 on 2024-03-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_transaction_dt_transaction_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccount",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="plaid_cursor",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
