# Generated by Django 5.0.2 on 2024-03-01 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_financialaccount_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="plaid_id",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="main.financialaccount",
            ),
        ),
    ]
