# Generated by Django 4.2.4 on 2024-02-29 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_subaccount_name_official"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subaccount",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "DEPOSITORY"),
                    (2, "INVESTMENT"),
                    (3, "LOAN"),
                    (4, "CREDIT"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="main.subaccount",
            ),
        ),
    ]
