# Generated by Django 5.0.2 on 2024-03-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_subaccount_ignored"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency_code",
            field=models.CharField(default="USD", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subaccount",
            name="sub_type",
            field=models.IntegerField(
                choices=[
                    (0, "CHECKING"),
                    (1, "SAVINGS"),
                    (2, "DEBIT_CARD"),
                    (3, "CREDIT_CARD"),
                    (4, "T401K"),
                    (5, "STUDENT"),
                    (6, "MORTGAGE"),
                    (7, "CD"),
                    (8, "MONEY_MARKET"),
                    (9, "IRA"),
                ]
            ),
        ),
    ]
