# Generated by Django 5.0.2 on 2024-03-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_transaction_notes_transaction_person_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="categories",
            field=models.TextField(),
        ),
    ]
