# Generated by Django 5.0.2 on 2024-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("date", "description", "amount")},
        ),
    ]
