# Generated by Django 5.0.2 on 2024-03-03 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_transaction_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetWorthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="net_worth_snapshots",
                        to="main.person",
                    ),
                ),
            ],
        ),
    ]
