# Generated by Django 5.0.2 on 2024-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_subaccount_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="subaccount",
            name="nickname",
            field=models.CharField(default="", max_length=30),
        ),
    ]
