# Generated by Django 5.0.2 on 2024-03-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_subaccount_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subaccount",
            name="sub_type",
            field=models.IntegerField(
                choices=[
                    (0, "CHECKING"),
                    (1, "SAVINGS"),
                    (2, "DEBIT_CARD"),
                    (3, "CREDIT_CARD"),
                    (4, "T401K"),
                    (5, "STUDENT"),
                    (6, "MORTGAGE"),
                    (7, "CD"),
                    (8, "MONEY_MARKET"),
                    (9, "IRA"),
                    (10, "STOCK_MUTUAL_FUND"),
                    (11, "CRYPTO"),
                    (12, "ASSET"),
                ]
            ),
        ),
    ]
