# Generated by Django 5.0.2 on 2024-03-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_snapshotaccount_snapshotperson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="logo_url",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_category_icon_url",
            field=models.CharField(default="", max_length=100),
        ),
    ]
