# Generated by Django 5.0.2 on 2024-03-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_transaction_logo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subaccount",
            name="name_official",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subaccount",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="logo_url",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="plaid_category_icon_url",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
