# Generated by Django 5.0.2 on 2024-03-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_subaccount_current"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryCusom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_cats",
                        to="main.person",
                    ),
                ),
            ],
        ),
    ]
