# Generated by Django 5.0.2 on 2024-03-10 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_categorycusom"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoryCusom",
            new_name="CategoryCustom",
        ),
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(choices=[(0, "INFLOW"), (1, "OUTFLOW")]),
                ),
                ("average_amount", models.FloatField()),
                ("last_amount", models.FloatField()),
                ("first_date", models.DateField()),
                ("last_date", models.DateField()),
                ("description", models.CharField(max_length=50)),
                ("merchange_name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("status", models.CharField(max_length=15)),
                ("categories", models.TextField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring",
                        to="main.subaccount",
                    ),
                ),
            ],
        ),
    ]
