# Generated by Django 5.0.2 on 2024-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_recurringtransaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="previous_emails",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
