# Generated by Django 5.0.2 on 2024-03-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_person_email_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
