# Generated by Django 5.0.2 on 2024-03-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_alter_person_email_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="institution_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institutions",
                to="main.institution",
            ),
        ),
    ]
