# Generated by Django 5.0.2 on 2024-03-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_transaction_institution_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="categories",
            field=models.JSONField(),
        ),
    ]
