# Generated by Django 5.0.2 on 2024-03-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_alter_categorycustom_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorycustom",
            options={},
        ),
        migrations.AlterField(
            model_name="categorycustom",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_cats",
                to="main.person",
            ),
        ),
    ]
