# Generated by Django 5.0.2 on 2024-03-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_financialaccount_last_refreshed_successfully"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="highlighted",
            field=models.BooleanField(default=False),
        ),
    ]
