# Generated by Django 5.0.2 on 2024-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_transaction_highlighted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringtransaction",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="categories",
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
