# Generated by Django 5.0.2 on 2024-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_recurringtransaction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="institution_name",
            field=models.CharField(max_length=100),
        ),
    ]
