# Generated by Django 5.0.2 on 2024-03-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_alter_financialaccount_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="financialaccount",
            unique_together={("person", "institution")},
        ),
    ]
