# Generated by Django 5.0.2 on 2024-03-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_alter_categoryrule_options_transaction_merchant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (-1, "UNCATEGORIZED"),
                            (2, "SOFTWARE_SUBSCRIPTIONS"),
                            (0, "GROCERIES"),
                            (1, "RESTAURANTS"),
                            (3, "TRAVEL"),
                            (4, "AIRLINES_AND_AVIATION_SERVICES"),
                            (5, "RECREATION"),
                            (6, "GYMS_AND_FITNESS_CENTERS"),
                            (7, "TRANSFER"),
                            (8, "DEPOSIT"),
                            (9, "INCOME"),
                            (10, "CREDIT_CARD"),
                            (11, "FAST_FOOD"),
                            (12, "DEBIT"),
                            (13, "SHOPS"),
                            (14, "PAYMENT"),
                            (15, "COFFEE_SHOP"),
                            (16, "TAXI"),
                            (17, "SPORTING_GOODS"),
                            (18, "ELECTRONICS"),
                            (19, "PETS"),
                            (20, "CHILDREN"),
                            (21, "MORTGAGE_AND_RENT"),
                            (22, "CAR"),
                            (23, "HOME_AND_GARDEN"),
                            (24, "MEDICAL"),
                            (25, "ENTERTAINMENT"),
                            (26, "BILLS_AND_UTILITIES"),
                            (27, "INVESTMENTS"),
                            (28, "FEES"),
                            (29, "TAXES"),
                            (30, "BUSINESS_SERVICES"),
                            (31, "CASH_AND_CHECKS"),
                            (32, "GIFTS"),
                            (33, "EDUCATION"),
                            (34, "ALCOHOL"),
                            (35, "HEALTH_AND_PERSONAL_CARE"),
                            (36, "CLOTHING"),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_items",
                        to="main.person",
                    ),
                ),
            ],
        ),
    ]
