# Generated by Django 5.0.2 on 2024-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0053_transaction_ignored"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycustom",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="institution",
            name="plaid_id",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="snapshotaccount",
            name="account_name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="subaccount",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=60, null=True),
        ),
    ]
