# Generated by Django 5.0.2 on 2024-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0055_alter_budgetitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date_registered",
            field=models.DateTimeField(default="1999-09-09"),
            preserve_default=False,
        ),
    ]
