# Generated by Django 5.0.2 on 2024-04-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0057_rename_last_refreshed_financialaccount_last_balance_refresh_attempt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="last_tran_refresh_attempt",
            field=models.DateTimeField(default="1999-09-09"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="last_tran_refresh_success",
            field=models.DateTimeField(default="1999-09-09"),
            preserve_default=False,
        ),
    ]
