# Generated by Django 5.0.2 on 2024-04-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0058_financialaccount_last_tran_refresh_attempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="needs_attention",
            field=models.BooleanField(default=False),
        ),
    ]
