# Generated by Django 5.0.2 on 2024-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0060_alter_financialaccount_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="subaccount",
            name="asset_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subaccount",
            name="asset_type",
            field=models.IntegerField(
                blank=True, choices=[(0, "Bitcoin"), (1, "Ethereum")], null=True
            ),
        ),
    ]
