# Generated by Django 5.0.2 on 2024-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_subaccount_asset_quantity_subaccount_asset_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subaccount",
            name="asset_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subaccount",
            name="asset_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Bitcoin"),
                    (1, "Ethereum"),
                    (2, "Bnb"),
                    (3, "Solana"),
                    (4, "Xrp"),
                ],
                null=True,
            ),
        ),
    ]
