# Generated by Django 5.0.2 on 2024-04-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0062_alter_subaccount_asset_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialaccount",
            options={"ordering": ["-last_tran_refresh_attempt"]},
        ),
        migrations.RemoveField(
            model_name="financialaccount",
            name="last_balance_refresh_attempt",
        ),
        migrations.RemoveField(
            model_name="financialaccount",
            name="last_balance_refresh_success",
        ),
    ]
