# Generated by Django 5.1.2 on 2025-01-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0063_alter_financialaccount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subaccount",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="subaccount",
            name="sub_type",
            field=models.IntegerField(
                choices=[
                    (0, "CHECKING"),
                    (1, "SAVINGS"),
                    (2, "DEBIT_CARD"),
                    (3, "CREDIT_CARD"),
                    (4, "T401K"),
                    (5, "STUDENT"),
                    (6, "MORTGAGE"),
                    (7, "CD"),
                    (8, "MONEY_MARKET"),
                    (9, "IRA"),
                    (10, "MUTUAL_FUND"),
                    (11, "CRYPTO"),
                    (12, "ASSET"),
                    (13, "BROKERAGE"),
                    (14, "ROTH"),
                    (15, "STOCK"),
                ]
            ),
        ),
    ]
