# Generated by Django 5.1.2 on 2025-01-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0064_alter_subaccount_name_alter_subaccount_sub_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycustom",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="institution",
            name="plaid_id",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="snapshotaccount",
            name="account_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="subaccount",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
